### PR TITLE
Footer is now at the end of the page

### PR DESCRIPTION
**Pull request by Bhargavamacha**
Footer is now at the end of the page

### CODE REVIEW

**Comment by 20Koen02** [comment]
#4

**Comment by ajwad-shaikh** [comment]
@Bhargavamacha Can you fix the conflicts due to a recent merge?

**Comment by Bhargavamacha** [comment]
sure

**Comment by Bhargavamacha** [comment]
Done

**Comment by Bhargavamacha** [comment]
Can you close all the Pull Requests?

**Comment by ajwad-shaikh** [comment]
@Bhargavamacha the conflicts are up again :(

**Comment by Bhargavamacha** [comment]
resolved

**Review by ajwad-shaikh — APPROVED** [review]

**Comment by ajwad-shaikh** [comment]
Thank you for your contribution @Bhargavamacha 
🌟 the repository to stay in the loop for further developments here

**Pull request merged**
